from . import test_contact
from . import test_enrollment
from . import test_enrollment_benefit
from . import test_enrollment_placement
from . import test_exit_management
from . import test_level
from . import test_level_tour
from . import test_study
from . import test_study_tour
from . import test_subject
from . import test_subject_tour
from . import test_outcome
from . import test_outcome_tour
from . import test_criteria
from . import test_criteria_tour
from . import test_content
from . import test_content_tour
from . import test_course
from . import test_course_tour
from . import test_company_settings
from . import test_settings
from . import test_employee_display_fields
from . import test_employee_tour
from . import test_attendance_template
from . import test_attendance_schedule
from . import test_attendance_status
from . import test_attendance_status_tour
from . import test_attendance_justification
from . import test_employee_role_group_sync
from . import test_employee_photo_visibility
from . import test_attendance_correction
from . import test_attendance_reports
from . import test_attendance_reports_tour
from . import test_grade_session
from . import test_grade_import_wizard
from . import test_applicant_import_wizard
from . import test_student_import_wizard
from . import test_planning
from . import test_data_custom_import_prefix
from . import test_data_main_cat_prefix
from . import test_security_group_references
from . import test_grade_session_tour
from . import test_employee_google_workspace
from . import test_employee_google_workspace_tour
from . import test_employee_ems_user
from . import test_strike
from . import test_strike_tour
from . import test_working_schedule
from . import test_ems_teaching_sync
from . import test_employee_schedule_lifecycle
from . import test_working_schedules_import_wizard
from . import test_task_assignment
from . import test_year_record
from . import test_non_teaching_type
from . import test_group
from . import test_group_schedule
from . import test_em_grading_wizard
from . import test_department
from . import test_company_director
from . import test_role
from . import test_role_color_tour
from . import test_department_color_tour
from . import test_attendance_template_color_tour
from . import test_withdrawal_tour
