name: Deploy on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: /root/myModules/ems/deploy.sh ${{ github.event.release.tag_name }}